### ISSUE TITLE
Hive support breakage in Spark 2.3

### ISSUE THREAD

**Issue by HugoHehn** [rstudio/sparklyr#1496]
Following a cluster upgrade I have been experiencing issues with sparklyr not finding Hive databases when connected to the Yarn client. Other than this everything seems to work - it is possible to load local data into a Spark dataframe and run operations on it.

Have done a lot of troubleshooting and searching solutions and most people seem to point to the hive-site.xml file. However, this looks to include all the necessary information and is stored in SPARK_HOME/conf as recommended.

Yarn and Spark seems to be able to find the Hive tables in Shell mode.

Versions used:

- R 3.4.1
- Hive 2.3.2
- Hue 4.1.0
- Spark 2.3.0

Code is basically just the package installation/loading plus:

```

Sys.setenv(SPARK_HOME = '/usr/lib/spark')

sc <- spark_connect(master="yarn-client", config=config, version = "2.3.0", hadoop_version = "2.8.3")

```

Has anyone had this issue?

**Comment by javierluraschi** [comment]
@HugoHehn could you elaborate on what got upgraded? Spark or also sparklyr? Would also help to see the stack trace and logs of the failed operation?

**Comment by harryprince** [comment]
@HugoHehn you can specific the hive-site.xml file in config like this:

```
config$`sparklyr.shell.files` = "/etc/hive/conf/hive-site.xml"
```

it will save your time.

**Comment by HugoHehn** [comment]
@javierluraschi  @harryprince 

Sorry about the late response. Issues still persist.

Cluster was upgraded to a newer EMR version along with newer versions of Spark and Hive. Sparklyr is reinstalled daily so it would also have updated, but it does not seem like that is the issue as reverting to earlier commit does not solve it.

No warning is printed as spark_connect() does not technically fail (it connects to Yarn as it should but does not see any Hive tables) but in the connection log there is a relevant warning:

```
18/05/30 12:18:30 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
18/05/30 12:18:31 INFO SharedState: loading hive config file: file:/etc/spark/conf.dist/hive-site.xml
18/05/30 12:18:31 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('hdfs:///user/spark/warehouse').
18/05/30 12:18:31 INFO SharedState: Warehouse path is 'hdfs:///user/spark/warehouse'.
```

Tried suggested solution from @harryprince  but based on above it seems like the issue might be related to spark.sql.warehouse.dir having a defualt value rather than the Hive home which then carries over to  the hive.metastore.warehouse.dir config. However, as all other applications on the cluster (incl. Spark in shell mode) finds the Hive context we are reluctant to tamper too much with the overall configs.

Not sure if there is a way to set spark.sql.warehouse.dir or hive.metastore.warehouse.dir within R. As far as I'm aware the setting is just ignored in favor of the hive-site.xml setting.

**Comment by HugoHehn** [comment]
@javierluraschi @harryprince 

Issue has been solved. Solution was that spark.sql.catalogImplementation needs to be set to "hive" in the spark-defaults.conf file.

**Comment by saurfang** [comment]
For 2.3.0, Hive support needs to be explicitly enabled when constructing in Spark Session. This is attempted here https://github.com/rstudio/sparklyr/blob/6c60c6eb9f5b29828b79594e834a49c6f3a86659/R/spark_hive.R#L33 but it doesn't quite work because at this point the Spark context has already been created.

In fact, `spark.sql.catalogImplementation` can't even be set via `spark_config` because this is a static configuration that cannot be changed after Spark context is initialized.

Currently, the only workaround is as mentioned by @HugoHehn using `spark-defaults.conf`. I consider this as a regression because sparklyr had been operating with the assumption that Hive is enabled by default.

**Comment by lcmercado** [comment]
I'm experiencing a similar issue because Spark connection is unable to detect Hive tables/databases. I'm following this [tutorial ](http://spark.rstudio.com/examples/yarn-cluster-emr/) step by step. It is provided by RStudio.

Versions used:
R version 3.4.1 (2017-06-30)
Spark 2.3.1
Sparkly R 0.8.4
Hive 2.3.3
Pig 0.17.0
Hue 4.2.0


I downloaded the latest RStudio version instead of the older version mentioned in the tutorial.  However, when I make the connection by running:  `sc <- spark_connect(master = "yarn-client", config = config, version = '2.3.1')` I don't see the Hive tables available as shown in the tutorial.

However, I know the tables exist because I can see them from console by running:
```
hive
show tables;
```

Already made sure that file **hive-site.xml**  is located in usr/lib/spark/conf directory.
Also, spark.sql.catalogImplementation is set to "hive" according to `hive_context_config(sc)`

Also, I noticed the sparklyR package has 2 functions related to Hive: **hive_context_config() and hive_context** 

Could somebody shed some light on how to use these functions to make a succesful connection to Hive? 

Not sure if there is an extra step required to make the Hive connection or maybe it is supposed to be created by default. In any case, the tutorial I'm using doesn't mention an extra step.

Any help is greatly appreciated.

**Comment by eddjberry** [comment]
I'm having this issue too with Spark 2.3.1 and sparklyr 0.8.4. I've tried @HugoHehn's solution of using `spark/conf/spark-defaults.conf`. In there I've got this
```
spark.sql.catalogImplementation     "hive"
```
I still can't see any Hive tables though. Like @lcmercado `hive_context_config(sc)` shows that spark.sql.catalogImplementation is set to "hive"

Spark 2.2.0 with sparklyr 0.7.0 works fine, as does SparkR with Spark 2.3.1.

**Comment by HugoHehn** [comment]
@lcmercado @eddjberry 

This is the line of code that solved our issues a few months back (the path obviously might need to be updated depending on your setup). Hope that it helps in your case as well.

``
echo "spark.sql.catalogImplementation  hive" |sudo tee -a /etc/spark/conf/spark-defaults.conf
``

**Comment by eddjberry** [comment]
Having looked through the code what we think we need to do is add is some shell arguments to the `spark-submit`. Specifically we want to pass in
```
shell_args <- paste0(
  "-Dspark.sql.catalogImplementation='hive'",
  " -Dhive.metastore.uris=",
  Sys.getenv("HIVE_METASTORE_URIS")
)
```

We tried this using the `sparklyr.shell.args` environment variable. However, this passed the arguments in as parameters to sparklyr.shell. 

We've also tried `config$`sparklyr.spark-submit` <- shell_args` but had no luck here either.

Finally, we thought passing `shell_args = shell_args` into `spark_connect()` might work, but it didn't.

**Comment by javierluraschi** [comment]
@eddjberry the `-Dspark.sql.catalogImplementation` seem to be related to `--driver-java-options` not plain `spark-submit` parameters, see https://stackoverflow.com/questions/47257680/unable-to-get-existing-hive-tables-from-hivecontext-using-spark.

So I would expect you want to connect with something like:

```r
conf <- spark_config()
conf[["sparklyr.shell.driver-java-options"]] <- paste0(
  "-Dspark.sql.catalogImplementation='hive' ",
  "-Dhive.metastore.uris=",
  Sys.getenv("HIVE_METASTORE_URIS")
)

sc <- spark_connect(master = "<master>", config = config)
```

Could you share the error log and how you expect `spark-submit` to be called? We should be able to, at least, get you `spark-submit` to trigger whichever parameters you are interested in triggering.

**Comment by genobobeno** [comment]
@eddjberry @javierluraschi 
I'm having the exact same issue. Running HDP 2.6.5, Spark 2.3.0, sparklyr 0.8.4, Hive 1.2.1000.
Now switching back to SparkR.

**Comment by bradleyhd** [comment]
Same problem here. sparklyr 0.8.4, spark 2.1.0, hive 2.1.1-amzn0 (on EMR, accessing via livy)

**Comment by kevinykuo** [comment]
Javier and I are out this week but we'll be looking into this as soon as we're back. To summarize,
1. Upgrading from Spark 2.2 to 2.3 breaks Hive when using sparklyr with `yarn-client` mode.
2. Some folks were able to work around this by modifying `spark-defaults.conf`, **but some others were not.** (Either way, having to mess with your conf file to make sparklyr work isn't ideal and should be fixed.)
3. This is related to the `spark.sql.catalogImplementation` option. However, the default in hasn't changed in Spark for a while, and it's not obvious skimming the change log which change is causing this issue.
4. sparklyr should consider refactoring the connection/backend to use `SparkSession` as the entry point for Spark 2.0+. Since we've been trying to support Spark 1.6+ we have made much changes and haven't ran into issues, until now. Maybe we just need to change the order of some config invocations, maybe we need to do more.
5. This issue can be repro'd through http://spark.rstudio.com/examples/yarn-cluster-emr/ as noted by @lcmercado. I haven't tried, but we'll investigate from there.

Let me know if this is mostly accurate, and any additional info/tips would also be helpful.

Relevant: https://github.com/holdenk/spark-testing-base/issues/234

**Comment by eddjberry** [comment]
@kevinykuo thanks for looking into this. The only thing that's different for me is that I'm using `master = 'yarn'` rather than `'yarn-client'`. I don't think this should make a difference though.

**Comment by sdanielzafar** [comment]
Thanks for the attention here I'm definitely open to setting aside some time to help debug this problem with one of you. Feel free to give me a shout.

**Comment by sdanielzafar** [comment]
@kevinykuo was there an update on this?

**Comment by kevinykuo** [comment]
@sdanielzafar Looking into this now, will report back with any findings.

@eddjberry if you intend to use yarn client mode, you should specify it in the `spark_connect()` call, otherwise (I think) it falls back to local mode.

**Comment by kevinykuo** [comment]
Update: I was able to repro on EMR with Spark 2.3.0 and dev sparklyr. I think we just need to catch the first time a `SparkSession` is initialized and make sure the config is passed properly. Coincidentally this is related to https://github.com/rstudio/sparklyr/pull/1639 which has a fix for properly caching the hive context. That change should be merged today and I'll pick up making any changes needed for this issue.

@eddjberry if you still can't get it to work after connecting via `master = "yarn-client"` and modifying `spark-defaults.conf`, please report back.

**Comment by kevinykuo** [comment]
Change has been merged. Things should work as expected *without* having to mess with your spark conf now. Please let me know if you continue to run into issues with this!

**Comment by soak0205** [comment]
i have made the required changes and still can't see the hive tables in the rstudio server panel. if i run result <- DBI::dbGetQuery(sc, 'show databases'), I do get the default database. However no tables on 'show tables' command though there are 3 tables in the default database.

**Comment by soak0205** [comment]
@eddjberry  is that done using devtools::install_github("rstudio/sparklyr")?
I did do that.

**Comment by soak0205** [comment]
i have no luck still....i see this in the rstudio logs...
`INFO metastore: Trying to connect to metastore with URI 
 INFO metastore: Connected to metastore.
`

**Comment by kevinykuo** [comment]
@soak0205 could you share more details on what your setup is (cloud, on-prem, which distribution, etc.), and also the code you're using to connect?

**Comment by soak0205** [comment]
AWS EMR with spark and hive
spark version - 2.3.1

 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.456) 

**code used to connect**
library(sparklyr)
Sys.setenv(SPARK_HOME="/usr/lib/spark")
config <- spark_config()
sc <- spark_connect(master = "yarn-client", version = "2.3.1", config = config)

**Comment by kevinykuo** [comment]
Could you try creating a Hive table before connecting and see if it shows up? Are the default tables on EMR documented somewhere? I don't remember seeing them...

**Comment by soak0205** [comment]
I have 3 tables created in hive before connecting. I see them through 'show tables' on hive prompt. But not through the rstudio result <- DBI::dbGetQuery(sc, 'show tables') command

Also, I realized that when i do show databases in hive, it shows be 3 databases. However, result <- DBI::dbGetQuery(sc, 'show databases') in RStudio shows only the default. 

But the metastore uri i see in the RStudio logs is the correct hive external metastore.

**Comment by cvrnogueira** [comment]
Here we were having the same issue and we were able to fix with @HugoHehn suggestion and we get sparklyr version from github :-)

**Comment by rayserrano2735** [comment]
Is this issue considered resolved, or is there still development work ongoing?

**Comment by kevinykuo** [comment]
This should be resolved but open an issue if you experience otherwise.

**Comment by okedoki** [comment]
The fix of @HugoHehn solved the problem.
Thanks.

One side note, in HDP(Hortonworks) you should do it via Ambari - Spark - Config- Custom spark2-defaults

**Comment by rayserrano2735** [comment]
I think there is still a bug.  Please see this:
https://github.com/rstudio/sparklyr/issues/1708

**Comment by harryprince** [comment]
sparklyr 2.3 support more ML functions, like `ft_quantile_discretizer` to batch quantile normlize features. hope to integrate Hive better inn sparklyr. Currently, `devtools::install_github("rstudio/sparklyr")` fail to solve the problem.

**Comment by rjsteckel** [comment]
Anyone else still having this issue? We just upgraded to Hortonworks 2.6.5.4-1 which uses spark 2.3 and now sparklyr (pull from github) fails when I run tbl_change_db(sc, '<db name>').

I can use hive and beeline just fine.

**Comment by kevinykuo** [comment]
@rjsteckel could you file an issue and link to https://github.com/rstudio/sparklyr/issues/1750 please

**Comment by rjsteckel** [comment]
Opened #1823

**Comment by tarunparmar** [comment]
I observed the same issue that sparklyr was not able to see hive tables with Spark 2.3.2 (I was using dataproc cluster in Google cloud). Had to setup up a new one with Spark 2.2.1 and the issue was gone.

**Comment by tdsmith** [comment]
I was experiencing this problem with sparklyr 0.9.4 on EMR with Spark 2.3.0, but adding `spark.sql.catalogImplementation	hive` to spark-defaults.conf did resolve it.

**Comment by kevinykuo** [comment]
@tdsmith `spark.sql.catalogImplementation` should default to `hive` if you don't pass anything to `config` in `spark_connect()`. Did it not work for you on EMR with the defaults?

**Comment by tdsmith** [comment]
Oddly, no, it didn't work.

Without `spark.sql.catalogImplementation hive` in spark-defaults.conf:
```
> sc <- spark_connect(master = "yarn")
> spark_config()
$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$sparklyr.connect.csv.embedded
[1] "^1.*"

$spark.sql.catalogImplementation
[1] "hive"

$sparklyr.connect.cores.local
[1] 16

$spark.sql.shuffle.partitions.local
[1] 16

attr(,"config")
[1] "default"
attr(,"file")
[1] "/home/hadoop/R/x86_64-redhat-linux-gnu-library/3.4/sparklyr/conf/config-template.yml"
> DBI::dbGetQuery(sc, "SHOW TABLES")
[1] database    tableName   isTemporary
<0 rows> (or 0-length row.names)
```

Notably, looking at the Spark UI, `spark.sql.catalogImplementation` does not appear on the environment tab.

After adding the line to the config file, `SHOW TABLES` has the expected result, and `spark.sql.catalogImplementation` shows up on the environment tab of the Spark UI.
