### ISSUE TITLE
Couple of issues with IDE "New Connection" dialog on Cluster

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#218]
RStudio Server Version 0.99.1259 on EMR 5.0 Cluster
This cluster uses Spark 2.0.0 and Hadoop 2.7.2

- In Spark tab, open New Connection dialog

1- In Master drop down field, select "yarn-client". This removes the option to select Spark and Hadoop version. And it defaults to Spark 1.6.2 and Hadoop 2.6.

2- Make these selections:
- Spark version: Spark 2.0.0
- Hadoop version: Hadoop 2.7  (the only matching one available)
- Then in Master: "local"

This prompts you to install Spark 2.0.0 for Hadoop 2.7 (it doesn't match with Hadoop 2.7.2). Go ahead with that. 
==> We need Hadoop 2.7.2 in the options.

3- In Master: "yarn-client - sparklyr"

This is invalid and causes SparkException. For these clusters we need "yarn-client" as an option.

**Comment by javierluraschi** [comment]
1. Removing Spark and Hadoop versions when `SPARK_HOME` is specified was the intended original design. Once you select `yarn-client` it should provide UI with something like `sc <- spark_connect(master = "yarn-client")` which would use the `SPARK_HOME` version and auto-discover which jar to deploy. From our chat, doesn't seem that there anything broken in this case. Ping me if I missed something.

 2. Right. The fix here is to ignore versions when `"local"` is selected AND `SPARK_HOME` is set. That should fix the particular issue we are pointing out here. Fixed with: https://github.com/rstudio/rstudio/compare/bugfix/noinstall-sparkhome?expand=1

 3. Correct, we need to split this up and assign the right `master` / `app_name`. Fixed with this one: https://github.com/rstudio/rstudio/pull/788

**Comment by fereshtehRS** [comment]
I know this is not fully fixed yet, but just an update:
RStudio Server Pro 1.0.20, sparklyr 0.3.14

a) If `SPARK_HOME` is not set, we get prompted with info about this and system admin. GOOD
b) Set `SPARK_HOME`, then bring up the dialog. 
 - Select `cluster`
 - Dialog pops up to enter `Spark master`
 - Enter `yarn-client` in the text field, and `OK`
 - Now the connection dialog shows:

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "spark://yarn-client")
```

Notice `spark::/yarn-client` string

  - Click on `Connect`. This causes error because of the invalid master:

```
Error: Failed during initialize_connection() org.apache.spark.SparkException: Invalid master URL: spark://yarn-client
```

**Comment by javierluraschi** [comment]
@fereshtehRS My intent was to have this already fully fixed. This seems like a new codepath that we want to improve, taking a look. Let me know if you find anything else appart from this last issue. I'll push a fix for todays IDE build.

**Comment by fereshtehRS** [comment]
@javierluraschi Haven't noticed anything else.

**Comment by javierluraschi** [comment]
@fereshtehRS I believe this can be closed now, ping me if you think that's not the case.
