### ISSUE TITLE
Issue building rsparkling package due to `sql_build` not found

### ISSUE THREAD

**Issue by navdeep-G** [rstudio/sparklyr#631]
Hi,

I recently tried to build `rsparkling` and got the following error in the R CMD CHECK:

`* checking for file ‘rsparkling/DESCRIPTION’ ... OK
* installing *source* package ‘rsparkling’ ...
** R
** inst
** preparing package for lazy loading
Error : object 'sql_build' not found whilst loading namespace 'sparklyr'
ERROR: lazy loading failed for package ‘rsparkling’
* removing ‘/Users/navdeepgill/Desktop/rsparkling.Rcheck/rsparkling’`

This is using `sparklyr` 0.5.3 currently uploaded to CRAN. Will there be a fix pushed soon? cc @javierluraschi @jjallaire @kevinushey .

An issue similar was also reported by @hadley when cross-checking his `dplyr` with `rsparkling`.

**Comment by kevinushey** [comment]
What version of `dplyr` do you have installed? (What is the output of `packageVersion("dplyr")`?)

**Comment by navdeep-G** [comment]
‘0.5.0.9004’, but a colleague of mine got a similar error 0.5.0, which is the one on CRAN.

**Comment by kevinushey** [comment]
That seems unlikely to me, since the current CRAN release of `dplyr` exports the `sql_build()` generic, whereas the development version of `dplyr` does not.

I don't know what the best solution for this is, unfortunately. Perhaps `sparklyr` should just define a duplicate `sql_build()` generic, or avoid using it altogether?

**Comment by ledell** [comment]
When using **sparklyr** 0.5.3 (latest CRAN) and **dplyr** 0.5.0 (from CRAN), I got the following error:
```r
> library(sparklyr)
Error : object 'db_data_type' not found whilst loading namespace 'sparklyr'
Error: package or namespace load failed for 'sparklyr'
```
I noticed that the **sparklyr** DESCRIPTION file imports **dplyr** (>=0.5.0.9001) though, so I updated all my packages and now I get a similar error:
```r
> library(sparklyr)
Error : object 'sql_build' not found whilst loading namespace 'sparklyr'
Error: package or namespace load failed for ‘sparklyr’
```
If I install **sparklyr** from GitHub, then it works just fine.  So whatever you did to fix these errors has been fixed on master, so maybe it's just time for a new release of sparklyr to CRAN?

**Comment by kevinushey** [comment]
I'm not able to reproduce that -- installing both CRAN dplyr + sparklyr works fine for me. You might need to make sure you're installing them in order:

```
install.packages("dplyr")
install.packages("sparklyr")
```

The current landscape is such that CRAN sparklyr works with CRAN dplyr, dev. sparklyr works with dev. dplyr, but currently 'crossing the streams' causes bad things to happen.

That said, it's possible that we'd be able to ensure that `sparklyr` is compatible with both CRAN and development `dplyr` with some extra work.

**Comment by navdeep-G** [comment]
Yes, but the issue remains with CRAN dplyr and CRAN sparklyr. Should the order of install really matter?

**Comment by kevinushey** [comment]
If you're installing packages from sources, then unfortunately it does. R populates some data structures related to S3 / S4 dispatch at package build time, and so if there is a mismatch between the packages used at load time, these sorts of errors can occur.

You can replicate with something like:

```
```

**Comment by hadley** [comment]
@kevinushey if this is going to cause general pain we should brainstorm some options

**Comment by kevinushey** [comment]
@hadley as far as I can tell, because CRAN `sparklyr` supplies methods for the `sql_build()` generic currently provided by CRAN `dplyr`, CRAN `sparklyr` will always be broken against the development version of `dplyr` unless the `sql_build()` generic is brought back (or provided through some other means).

**Comment by kevinushey** [comment]
Maybe `dplyr` should continue exporting the `sql_build` generic for now, but let `dbplyr` implement all the methods of interest?

**Comment by kevinushey** [comment]
FYI, continued discussion is at https://github.com/tidyverse/dplyr/issues/2670.

I think we're going to try to submit a new version of `sparklyr` that will be compatible with both dplyr 0.5.0 and dplyr 0.6.0.

**Comment by navdeep-G** [comment]
@kevinushey Yes, I think submitting a new version of `sparklyr` to CRAN would be the best solution. 

cc @ledell

**Comment by javierluraschi** [comment]
@navdeep-G @ledell In general, we only support `sparklyr` and `dplyr` installed from CRAN or `sparklyr` and `dplyr` installed from Github. That said, as suggested in this thread, we've prepared a patch to support `sparklyr` installed from CRAN with `dplyr` installed from Github, mostly, as preparation to support `dplyr 0.6`.

If you could try out this patch release, it would be much appreciated, you can find this release here: https://github.com/rstudio/sparklyr/releases/tag/v0.5.4

**Comment by javierluraschi** [comment]
`0.5.4` is on CRAN now: https://cran.r-project.org/web/packages/sparklyr/index.html
